server:
  port: 8085
spring:
  application:
    name: notification
  config:
    import: optional:classpath:network-dev.yml
  datasource:
    url: jdbc:mysql://s3lab-1.cns4oy2ay0sd.ap-southeast-2.rds.amazonaws.com:3306/ems_001?useSSL=false&serverTimezone=UTC
    username: admin
    password: zxc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    userName: s3labofficial@gmail.com
    password: vvmi cwbp lgly vpru

jwt:
  secret: 0191eb1feacf719c898518c598134bba4ac6dead4464943885810c7d3938c26
  expiration: 3600000
  refreshExpiration: 604800000